export const Pages = {
  GetStartedUI: "get-started.html", 
  SignInUI: "signin.html", 
  SignUpUI: "signup.html", 
  EnterCodeUI: "enter-code.html", 
  ForgotPasswordUI: "forgot-password.html", 
  ResetPasswordUI: "reset-password.html", 
  PrivacyPolicyUI: "privacy-policy.html",
  CookiesPolicyUI: "coockies-policy.html",
  TermsUI: "terms.html",
  DashboardUI: "dashboard.html", 
//-----------------------------------
  SettingsUI: "settings.html", 
  NotificationsUI: "notifications.html", 
  AboutUsUI: "about-us.html", 
  AddVehiclesUI: "add-vehicles.html", 
  PredictMaintenanceUI: "predict-maintenance.html", 
  ShowPredictionsUI: "show-predictions.html", 
  TrackVehicleUI: "track-vehicle.html", 
  AutoMobSearchUI: "automob-search.html",
  AutoMobDetailsUI: "automob-details.html",
  BreakdownAssistUI: "breakdown-assistance.html",
  EmergencyAssistUI: "emergency-assistance.html",
  ManageDocumentsUI: "documents.html",
  AddSRecordManualUI: "add-record.html",
  QrUI: "qr-ui.html",
  AddRecordBySPUI: "add-record-sp.html",
  ShowRecordReqUI: "show-record-request.html",
  ParkingFinderUI: "parking-finder.html",
  ParkingInfoUI: "parking-info.html",
  ViewVehicle: "view-vehicle.html",
};
